name = "bab-proxy-worker"
compatibility_date = "2025-05-07"
main = "./worker/worker.js"

# Define the route to match https://soydev.life/bab/*
[routes]
pattern = "soydev.life/bab/*"
zone_name = "soydev.life"